spring:
  main:
    banner-mode: 'OFF'
    
  ### devtools ###
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      
  ### datasource ###
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  messages:
    encoding: UTF-8
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootdb
    username: sa
    
  h2:
    console:
      enabled: true
      
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-timeout: 60000
#      maximum-pool-size: 20
#    password: deploypw
#    url: jdbc:mysql://172.18.186.21:3306/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: deployadmin

  kafka:
      #admin:
      #  properties:
      #   security.protocol: SSL
      bootstrap-servers: localhost:9092
      consumer:
        group-id: paingan
        fetch-min-size: 1
        max-poll-records: 1000
        
      admin:
        fail-fast: true
      
      
  mvc:
    favicon:
      enabled: true

   

  liquibase:
    enabled: false
    change-log: classpath:liquibase-outputChangeLog.xml  
    
  social:
    google:
      appId: 69362329948-o0hia1jdag0keb43bddasvvmhqn6ik49.apps.googleusercontent.com
      appSecret: A-Q8VUrsxKgMl1Cbt-S2CMfy
      
      
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 69362329948-o0hia1jdag0keb43bddasvvmhqn6ik49.apps.googleusercontent.com
            clientSecret: A-Q8VUrsxKgMl1Cbt-S2CMfy


### logger ###
logging.file: paingan-boot.log
logging:
  level:
    root: ERROR
    org.springframework.security: ERROR
    org.springframework.web: INFO
    org.paingan.boot: DEBUG
    org.hibernate: ERROR
  file:
    max-history: 20
    max-size: 50MB
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    
    
application:
  name: Paingan Boot v1.0.3 (development mode)
  

info:
  app:
    name: Paingan Boot (dev)
    description: This is my first spring boot application
    version: 3.0.0


### actuator ###      
management:
  endpoints:
    web: 
      exposure:
        include: "*"
#    enabled-by-default: false 
  info:
    defaults:
      enabled: true
#  endpoint:
#    shutdown:
#      enabled: true


### server ###  
#server:
#  port: 8082

boot:
  kafka:
    topic: paingan-event
    
kafka:
    topic: paingan-event
