# default port configuration
server:
  error:
    whitelabel:
      enabled: false
  port: 8082
  
# default profile
spring:
  application:
    name: Paingan Boot
  profiles:
    active: thym, dev #heroku
    
logging:
  level:
    ROOT: INFO

# common properties    
header:
  title: Paingan Boot - Spring Boot Examples
  

  