spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
    password: y5imuwxjnlsgfrrw
    url: jdbc:mysql://yup5s49ny1t8zgee:y5imuwxjnlsgfrrw@jj820qt5lpu6krut.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/lb64fl8b9h7sxbit?autoReconnect=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: yup5s49ny1t8zgee
  liquibase:
    #change-log: classpath:liquibase-outputChangeLog.xml
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml  