spring:
  main:
    banner-mode: 'OFF'
    
  ### devtools ###
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      
  ### datasource ###
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  messages:
    encoding: UTF-8
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    
  h2:
    console:
      enabled: true
      
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-timeout: 60000
#      maximum-pool-size: 20
#    password: deploypw
#    url: jdbc:mysql://172.18.186.21:3306/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: deployadmin
      
  mvc:
    favicon:
      enabled: true
   

  liquibase:
    enabled: false
    change-log: classpath:liquibase-outputChangeLog.xml  


### logger ###
logging:
  level:
    root: ERROR
    org.springframework.security: ERROR
    org.springframework.web: INFO
    org.paingan.boot: DEBUG
    org.hibernate: ERROR
    
    
application:
  name: Paingan Boot v1.0.3 (development mode)
  

info:
  app:
    name: Paingan Boot (dev)
    description: This is my first spring boot application
    version: 3.0.0


### actuator ###      
management:
  endpoints:
    web: 
      exposure:
        include: "*"
#    enabled-by-default: false 
  info:
    defaults:
      enabled: true
#  endpoint:
#    shutdown:
#      enabled: true


### server ###  
#server:
#  port: 8082
