spring:
  main:
    banner-mode: 'OFF'
    
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    encoding: UTF-8
    
  h2:
    console:
      enabled: false
      
  mvc:
    favicon:
      enabled: true
      
  liquibase:
    enabled: false
    change-log: classpath:liquibase-outputChangeLog.xml  


# logger ---- 
logging:
  level:
    root: ERROR
    org.springframework.security: ERROR
    org.springframework.web: INFO
    org.paingan.boot: DEBUG
    org.hibernate: ERROR
    
    
application:
  name: Paingan Boot v1.0.3 (development mode)
  

info:
  app:
    name: Paingan Boot (dev)
    description: This is my first spring boot application
    version: 3.0.0
      
management:
  endpoints:
    web: 
      exposure:
        include: "*"
#    enabled-by-default: false 
  info:
    defaults:
      enabled: true
#  endpoint:
#    shutdown:
#      enabled: true
   
server:
  port: 8082
